sudo rm /var/www/kindle/active/0.txt
sudo rm /var/www/kindle/active/1.txt
sudo rm /var/www/kindle/active/1a.txt
sudo rm /var/www/kindle/active/1.2.txt
sudo rm /var/www/kindle/active/1.3.txt
sudo rm /var/www/kindle/active/1.4.txt
sudo rm /var/www/kindle/active/1.5.txt
sudo rm /var/www/kindle/active/1.6.txt
sudo rm /var/www/kindle/active/1.7.txt
sudo rm /var/www/kindle/active/1.8.txt
sudo rm /var/www/kindle/active/1.8b.txt
sudo rm /var/www/kindle/active/1.9.txt
sudo rm /var/www/kindle/active/1.9b.txt
sudo rm /var/www/kindle/active/1.10.txt
sudo rm /var/www/kindle/active/1.10b.txt
sudo rm /var/www/kindle/active/1.11.txt
sudo rm /var/www/kindle/active/1.11b.txt
sudo rm /var/www/kindle/active/1.12.txt
sudo rm /var/www/kindle/active/phrases.1.txt
sudo rm /var/www/kindle/active/single-words.1.txt
sudo rm /var/www/kindle/active/single-words.2.txt
sudo rm /var/www/kindle/active/single-words.3.txt
sudo rm /var/www/kindle/active/single-words.4.txt
sudo rm /var/www/kindle/active/phrases.1.txt
sudo rm /var/www/kindle/active/phrases.2.txt
sudo rm /var/www/kindle/active/phrases.3.txt
sudo rm /var/www/kindle/active/phrases.4.txt
